Portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from Authentification.views import accueil_admin_Appli, accueil_admin
from Resume.views import accueil_visiteur, index_page, accueil
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_page, name='index'),
    path('accueil/', accueil, name='accueil'),
    path('manage/', accueil_admin_Appli, name='accueil-APPLI'),
    path('accueil/admin/', accueil_admin, name='accueil-admin'),
    path('<str:personnel>/', accueil_visiteur, name='accueil-visiteur'),
    path('auth/', include('Authentification.urls')),
    path('resume/', include('Resume.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Resume/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('profil/', mon_profil, name='mon-profil'),
    path('personnels/', tout_personnel, name='tout-personnel'),
    path('personnel/ajout/', Ajout_personnel, name='ajout-personnel'),
    path('personnel/<int:id>/modifier/', Ajout_personnel, name='modif-personnel'),
    path('competence/ajout/', Ajout_competence, name='ajout-competence'),
    path('competence/<int:id>/modifier/', Ajout_competence, name='modif-competence'),
    path('services/ajout/', Ajout_service, name='ajout-service'),
    path('services/<int:id>/modifier/', Ajout_service, name='modif-service'),
    path('realisations/ajout/', Ajout_realisation, name='ajout-realisation'),
    path('realisations/<int:id>/modifier/', Ajout_realisation, name='modif-realisation'),
    path('experience_academique/ajout/', Ajout_exp_Academique, name='ajout-expAca'),
    path('experience_academique/<int:id>/modifier/', Ajout_exp_Academique, name='modif-expAca'),
    path('experience_professionnel/ajout/', Ajout_exp_Professionnel, name='ajout-expPro'),
    path('experience_professionnel/<int:id>/modifier/', Ajout_exp_Professionnel, name='modif-expPro'),
    
    path('galerie/ajout/', ajout_photo_galerie, name='ajout-photo-galerie'),
]

Resume/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Personnel(models.Model):
    def __str__(self):
        return f'{self.nom}'
    
    sexe_choix = [
        ('Masculin', 'Masculin'),
        ('Feminin', 'Feminin'),
    ]
    nom = models.CharField(max_length=30, verbose_name='Nom', blank=True, null=True)
    prenom = models.CharField(max_length=30, verbose_name='Prenom', blank=True, null=True)
    sexe = models.CharField(max_length=10, verbose_name='Sexe', choices=sexe_choix, blank=True, null=True)
    date_naissance = models.DateField(verbose_name='Date de naissance', blank=True, null=True)
    telephone_1 = models.CharField(max_length=30, verbose_name='Telephone', blank=True, null=True)
    telephone_2 = models.CharField(max_length=30, verbose_name='Telephone', blank=True, null=True)
    email = models.EmailField(max_length=30, verbose_name='E-mail', blank=True, null=True)
    pays = models.CharField(max_length=30, verbose_name='Pays', blank=True, null=True)
    ville = models.CharField(max_length=30, verbose_name='ville', blank=True, null=True)
    resume = models.TextField(max_length=500, verbose_name='Resumé', blank=True, null=True)
    motivation = models.TextField(max_length=300, verbose_name='Motivations personnelles', blank=True, null=True)

    profil_actuel = models.CharField(max_length=100, verbose_name='Profil actuel', blank=True, null=True)
    description_profil = models.CharField(max_length=255, verbose_name='Description du profil', blank=True, null=True)

    date_created = models.DateField(verbose_name='Date creation', auto_now=True)

    def lien(self):
        if self.nom is not None and self.prenom is not None:
            return f'{self.nom}_{self.prenom}_{self.id}'
        elif self.nom is not None and self.prenom is None:
            return f'{self.nom}_{self.id}'
        
    def Age(self):
        today = timezone.now()
        age = today.year - self.date_naissance.year
        #age = diff.days // 365
        agestr = f'{age} ans'
        if age == 1:
            agestr = f'{age} an'
        if age<1:
            age = today.month - self.date_naissance.month
            agestr = f'{age} mois'
            if age < 1:
                age = today.day - self.date_naissance.day
                agestr = f'{age} jours'

        return agestr
    
class Competences(models.Model):
    def __str__(self):
        return f'{self.competence}'
    
    personnel = models.ForeignKey(Personnel, on_delete=models.SET_NULL, related_name='competencesperso', null=True, blank=True)
    competence = models.CharField(max_length=100, verbose_name='Competence', blank=True, null=True)
    description = models.CharField(max_length=200, verbose_name='Description de la compétence', blank=True, null=True)
    niveau = models.IntegerField(verbose_name='Niveau(%)', blank=True, null=True)
    date_created = models.DateField(verbose_name='date_created', blank=True, null=True, auto_now=True)   
    
class Services_proposes(models.Model):
    def __str__(self):
        return f'{self.competence}'
    
    personnel = models.ForeignKey(Personnel, on_delete=models.SET_NULL, related_name='serviceperso', null=True, blank=True)
    service = models.CharField(max_length=100, verbose_name='Services proposés', blank=True, null=True)
    description = models.CharField(max_length=200, verbose_name='Description du service', blank=True, null=True)
    photo = models.ImageField(verbose_name='Icone du service', upload_to='media/services/', blank=True, null=True)
    date_created = models.DateField(verbose_name='date_created', blank=True, null=True, auto_now=True)   

class Experience_Academique(models.Model):
    def __str__(self):
        return f'{self.ecole} {self.filiere}'
    
    statut_choix = [
        ('En cours', 'En cours'),
        ('Terminé', 'Terminé'),
    ]
    personnel = models.ForeignKey(Personnel, on_delete=models.SET_NULL, related_name='ExpAcad', null=True, blank=True)
    annee_debut = models.IntegerField(verbose_name='Année debutée', blank=True, null=True)
    annee_fin = models.IntegerField(verbose_name='Année fini', blank=True, null=True)
    ecole = models.CharField(max_length=50, verbose_name='Etablissement', blank=True, null=True)
    filiere = models.CharField(max_length=50, verbose_name='Filière', blank=True, null=True)
    diplome = models.CharField(max_length=50, verbose_name='Diplome', blank=True, null=True)
    pays = models.CharField(max_length=50, verbose_name='Pays', blank=True, null=True)
    ville = models.CharField(max_length=50, verbose_name='Ville', blank=True, null=True)

    staut = models.CharField(max_length=30, verbose_name='Statut', choices=statut_choix,blank=True, null=True)
    date_created = models.DateField(verbose_name='date_created', blank=True, null=True, auto_now=True)

class Experience_Professionnelle(models.Model):
    def __str__(self):
        return f'{self.competence}'
    
    statut_choix = [
        ('En cours', 'En cours'),
        ('Terminé', 'Terminé'),
    ]
    personnel = models.ForeignKey(Personnel, on_delete=models.SET_NULL, related_name='ExpPro', null=True, blank=True)
    date_debut = models.DateField(verbose_name='Date debut', blank=True, null=True)
    date_fin = models.DateField(verbose_name='Date fin', blank=True, null=True)
    entreprise = models.CharField(max_length=70, verbose_name='Nom de la structure', blank=True, null=True)
    poste = models.CharField(max_length=50, verbose_name='Poste', blank=True, null=True)
    description = models.CharField(max_length=150, verbose_name='Description du poste', blank=True, null=True)
    pays = models.CharField(max_length=50, verbose_name='Pays', blank=True, null=True)
    ville = models.CharField(max_length=50, verbose_name='Ville', blank=True, null=True)

    staut = models.CharField(max_length=30, verbose_name='Statut', choices=statut_choix,blank=True, null=True)
    date_created = models.DateField(verbose_name='date_created', blank=True, null=True, auto_now=True)

class Realisation(models.Model):
    def __str__(self):
        return f'{self.realisation}'
    
    personnel = models.ForeignKey(Personnel, on_delete=models.SET_NULL, related_name='realiseperso', null=True, blank=True)
    realisation = models.CharField(max_length=100, verbose_name='Lien du projet', blank=True, null=True)
    description = models.CharField(max_length=200, verbose_name='Description du projet', blank=True, null=True)
    date_created = models.DateField(verbose_name='date_created', blank=True, null=True, auto_now=True)   

class Image_realisation(models.Model):
    def __str__(self):
        return f'{self.realisation}'
    
    realisation = models.ForeignKey(Realisation, on_delete=models.SET_NULL, related_name='imgReali', null=True, blank=True)
    photo = models.ImageField(verbose_name='Image de la realisation', upload_to='realisations/', blank=True, null=True)
    date_created = models.DateField(verbose_name='date_created', blank=True, null=True, auto_now=True)   
    
class Galerie_perso(models.Model):
    def __str__(self):
        return f'{self.personnel}'
    
    personnel = models.ForeignKey(Personnel, on_delete=models.SET_NULL, related_name='GaleriPerso', null=True, blank=True)
    photo = models.ImageField(verbose_name='Image de la realisation', upload_to='galerie', blank=True, null=True)
    #description = models.CharField(max_length=200, verbose_name='Description de l\'image', blank=True, null=True)
    date_created = models.DateField(verbose_name='date_created', blank=True, null=True, auto_now=True)   
    
class Reglage(models.Model):
    personnel = models.ForeignKey(Personnel, on_delete=models.SET_NULL, related_name='ReglagePerso', null=True, blank=True)
    photo_profil = models.ForeignKey(Galerie_perso, on_delete=models.SET_NULL, related_name='profilperso', null=True, blank=True)
    photo_couverture = models.ForeignKey(Galerie_perso, on_delete=models.SET_NULL, related_name='couvertureperso', null=True, blank=True)
    poste_actuel = models.ForeignKey(Experience_Professionnelle, on_delete=models.SET_NULL, related_name='posteactuel', null=True, blank=True)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Tout savoir sur moi !</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png '%}" rel="apple-touch-icon">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/aos/aos.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bootstrap-icone/font/bootstrap-icons.css' %}" />
    
    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: MyResume
    * Template URL: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/
    * Updated: Mar 17 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
    </head>
    <body class="bg-light d-flex flex-column small min-vh-100">
        {% if banniere == False %}
        {% else %}
            <div class="row m-0 small"  style="background-color: #c1ccfd;">
                <div class="col-4 m-0 p-0">
                <img src="{% static 'img/favicon.png' %}" class="shadow-sm rounded-3" width="100" height="75" alt="">
                </div>
                <div class="col m-auto small">
                {% if user.is_authenticated %}
                    <a href="{% url 'accueil-admin' %}" class="btn btn-outline-primary rounded-5 m-1"> Mon profil </a>
                {% else %}
                    <a href="" class="btn btn-outline-primary btn-sm rounded-5"> Connexion </a>
                    <a href="" class="btn btn-outline-dark btn-sm rounded-5"> inscription </a>
                {% endif %}
                
                </div>
            </div>
        {% endif %}
        <!-- if request.user.is_authenticat -->
        <!-- ======= Mobile nav toggle button ======= -->
        <!-- <button type="button" class="mobile-nav-toggle d-xl-none"><i class="bi bi-list mobile-nav-toggle"></i></button> -->
        <i class="bi bi-list mobile-nav-toggle d-lg-none"></i>
        <!-- ======= Header ======= -->
        <header id="header" class="d-flex flex-column justify-content-center">

            <nav id="navbar" class="navbar nav-menu" style="min-width: 20vw;">
            <ul>
                {% if type == 'rien' %}
                <li><a href="{% url 'accueil' %}" class="nav-link scrollto"><i class="bi bi-house"></i> <span>Accueil</span></a></li>
                {% elif type == 'dashbord' %}
                <li><a href="#dashbord" class="nav-link scrollto active"><i class="bi bi-speedometer2"></i> <span>Tableau de bord</span></a></li>
                <li><a href="#personnel_list" class="nav-link scrollto" ><i class="bx bx-user"></i> <span>Clients</span></a></li>
                {% elif type == 'index' %}
                <li><a href="#information" class="nav-link scrollto active"><i class="bi bi-house"></i> <span>Accueil</span></a></li>
                <li><a href="#services" class="nav-link scrollto" ><i class="bx bx-server"></i> <span>Services</span></a></li>
                <li><a href="#about" class="nav-link scrollto" ><i class="bi bi-people"></i> <span>A propos</span></a></li>
                {% elif type == 'manage' %}
                <li><a href="?information" class="nav-link scrollto {% if 'information' in url %}active{%endif%}"><i class="bi bi-info"></i> <span>Informations</span></a></li>
                <li><a href="?resume" class="nav-link scrollto {%if 'resume' in url %}active{%endif%}"><i class="bi bi-book"></i> <span>Resume</span></a></li>
                <li><a href="?exp_academique" class="nav-link scrollto {%if 'exp_academique' in url %}active{%endif%}"><i class="bi bi-headset-vr"></i> <span>Experience academique</span></a></li>
                <li><a href="?exp_professionnel" class="nav-link scrollto {%if 'exp_professionnel' in url %}active{%endif%}"><i class="bi bi-radioactive"></i> <span>Experience professionnelle</span></a></li>
                <li><a href="?competences" class="nav-link scrollto {%if 'competences' in url %}active{%endif%}"><i class="bi bi-brilliance"></i> <span>Competences</span></a></li>
                <li><a href="?services" class="nav-link scrollto {%if 'services' in url %}active{%endif%}"><i class="bi bi-server"></i> <span>Services</span></a></li>
                <li><a href="?realisation" class="nav-link scrollto {%if 'realisation' in url %}active{%endif%}"><i class="bi bi-lamp-fill"></i> <span>Réalisations</span></a></li>
                <li><a href="?autre" class="nav-link scrollto {%if 'autre' in url %}active{%endif%}"><i class="bi bi-lamp-fill"></i> <span>Autres</span></a></li>

                {% else %}
                <li><a href="#hero" class="nav-link scrollto active"><i class="bx bx-home"></i> <span>Home</span></a></li>
                <li><a href="#about" class="nav-link scrollto"><i class="bx bx-user"></i> <span>About</span></a></li>
                <li><a href="#resume" class="nav-link scrollto"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
                <li><a href="#portfolio" class="nav-link scrollto"><i class="bx bx-book-content"></i> <span>Portfolio</span></a></li>
                <li><a href="#services" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Services</span></a></li>
                <li><a href="#contact" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>
                {% endif %}
            </ul>
            </nav><!-- .nav-menu -->

        </header><!-- End Header -->
        <!-- endif -->

        {% block content %}
        
        {% endblock content %}
        
        <!-- ======= Footer ======= -->
        <!-- if request.user.is_authenti -->

        <footer id="footer" class="small py-3 mt-auto bg-white">
            <div class="container">
            <!-- <h3>Brandon Johnson</h3>
            <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p> -->
            <div class="social-links">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
            <div class="copyright">
                &copy; Copyright <strong><span>Portfolio</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: [license-url] -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->
                Designed by <a href="#">Wahb's</a>
            </div>
            </div>
        </footer><!-- End Footer -->
        <!--  endif  -->

        <div id="preloader"></div>
        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

        <!-- Vendor JS Files -->
        <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
        <script src="{% static 'vendor/aos/aos.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'vendor/typed.js/typed.umd.js' %}"></script>
        <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
        <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

        <!-- Template Main JS File -->
        <script src="{% static 'js/main.js' %}"></script>

    </body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    
<main class="">
  
  <section class="min-vh-100" style="background-image:url({% static 'img/bg.png' %});background-position:top center;background-size:cover;" id="information">
    <div class="container"  data-aos="fade-up" data-aos-delay="100">
      <div class="col-lg-10 m-auto">
        <span class="card-title h2">
          <img src="{% static 'img/sommaire.png' %}" width="50" height="50" alt=""> Créez un Cv de qualité ! 
        </span> <br>
        <span class="card-subtitle">
          Nous vous aiderons à produire un document digne de votre profil.
        </span>
        <br>
        <span class="card-subtitle">
          Prenez en main votre profil et montrez au monde entier qui vous êtes. <br>
          Nous vous offrons : <br>
        </span>
      </div>
      <div class="row m-3">
        <div class="col-10 m-auto">
          <span class="h6"><i class="bi bi-check-circle text-success"></i> Site web personnalisé <br></span>
          <span class="h6"><i class="bi bi-check-circle text-success"></i> Production du CV <br></span>
          <span class="h6"><i class="bi bi-check-circle text-success"></i> Votre portfolio complet <br></span>
        </div>
      </div>
      <div class="container m-auto text-end flex-column d-flex">
        <div class="row m-5">
          <div class="col m-5">
            <a href="{% url 'ajout-personnel' %}" class="btn btn-primary btn-lg rounded-5"> Lancer <i class="bi bi-arrow-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </section>
    

    <!-- Feature services -->
    <section id="services" class="featured-services min-vh-100"  style="background-image:url({% static 'img/bg.png' %});background-position:top center;background-size:cover;">
      <div class="row">
        <div class="col m-2 text-center">
          <span class="h2"> Nos services d'experts </span>
        </div>
      </div>  
      <div class="container aos-init aos-animate " data-aos="fade-up">
          
          <div class="row ">
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-5 mb-lg-3">
              <div class="icon-box aos-init" data-aos="fade-up" data-aos-delay="100">
                <div class="icon text-center"><img src="{% static 'img/consultant.png' %}" width="100" height="100" alt=""></div>
                <h4 class="title"><a href="">Consultant en informatique</a></h4>
                <p class="description">
                  Nous fournissons des conseils et des orientations d'experts sur diverses questions liées aux technologies de l'information, telles que la stratégie technologique, la mise en œuvre et l'optimisation.
                </p>
              </div>
            </div>
  
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-5 mb-lg-3">
              <div class="icon-box aos-init" data-aos="fade-up" data-aos-delay="200">
                <div class="icon text-center"><img src="{% static 'img/programmeur.png' %}" width="100" height="100" alt=""></div>
                <h4 class="title"><a href="">Developpement de logiciels</a></h4>
                <p class="description">
                  Nous concevons, développons et gérons des applications et des systèmes logiciels pour des entreprises, des organisations ou des particuliers.
                </p>
              </div>
            </div>
  
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-5 mb-lg-3">
              <div class="icon-box aos-init" data-aos="fade-up" data-aos-delay="300">
                <div class="icon text-center"><img src="{% static 'img/creation-de-sites-web.png' %}" width="100" height="100" alt=""></div>
                <h4 class="title"><a href="">Conception et developpement de site web</a></h4>
                <p class="description">
                  Nous créons et gérons des sites web, des applications web et des portails en ligne pour les entreprises et les organisations.
                </p>
              </div>
            </div>

            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-5 mb-lg-3">
              <div class="icon-box aos-init" data-aos="fade-up" data-aos-delay="400">
                <div class="icon text-center"><img src="{% static 'img/mobile.png' %}" width="100" height="100" alt=""></div>
                <h4 class="title"><a href="">Developpement d'application mobile</a></h4>
                <p class="description">
                  Nous développons des applications mobiles pour smartphones et tablettes, qui peuvent aider les entreprises à se connecter avec leurs clients et clients.
                </p>
              </div>
            </div>

            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-5 mb-lg-3">
              <div class="icon-box aos-init" data-aos="fade-up" data-aos-delay="400">
                <div class="icon text-center"><img src="{% static 'img/data-analyst.png' %}" width="100" height="100" alt=""></div>
                <h4 class="title"><a href="">Analyse des données</a></h4>
                <p class="description">
                  Nous appliquons des outils et des techniques d'analyse de données pour aider vos entreprises et vos organisations à mieux comprendre leurs opérations, leurs clients et leurs marchés.
                </p>
              </div>
            </div>


            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-5 mb-lg-3">
              <div class="icon-box aos-init" data-aos="fade-up" data-aos-delay="400">
                <div class="icon text-center"><img src="{% static 'img/data-science.png' %}" width="100" height="100" alt=""></div>
                <h4 class="title"><a href="">L'IA et le Machine Learning</a></h4>
                <p class="description">
                  Nous développons des solutions et des systèmes basés sur l'IA pour vos entreprises et organisations afin d'améliorer l'efficacité et la prise de décision.
                </p>
              </div>
            </div>

  
          </div>
  
        </div>
    </section>

    <!-- ********** Section à propos ********************* -->
    
    <section class="min-vh-100" style="background-image:url({% static 'img/bg.png' %});background-position:top center;background-size:cover;" id="about">
      <div class="container"  data-aos="fade-up" data-aos-delay="100">
        <div class="col-lg-10 m-auto">
          <span class="card-title h2">
            <div class="row">
              <div class="col-3">
                <img src="{% static 'img/communaute.png' %}" width="50" height="50" alt=""> 
              </div>
              <div class="col m-0 p-0">
                Nous sommes une communauté active d'informaticiens
              </div>
            </div>
          </span> <br>
          <span class="card-subtitle">
            Capable de resoudre des problemes complexes,
          </span>
          <br>
          <span class="card-subtitle">
            Nos solutions sont toutes exceptionnelles ! <br>
          </span>
        </div>

        <div class="row">
          <div class="col-lg-5 m-auto">

          </div>
          <div class="col-lg-7 m-auto">
            <form action="" name="form" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="form-floating mt-1">
                  <input type="text" name="nom" id="id_nom" class="form-control form-control-sm rounded-5 ps-4" placeholder="Nom complet">
                  <label for="id_nom" class="form-label ms-3"> Nom complet</label>
                </div>
                <div class="form-floating col-lg-6 mt-1">
                  <input type="text" name="phone" id="id_phone" class="form-control form-control-sm rounded-5 ps-4" placeholder="Telephone">
                  <label for="id_phone" class="form-label ms-3"> Telephone </label>
                </div>
                <div class="form-floating col-lg-6 mt-1">
                  <input type="email" name="email" id="id_email" class="form-control form-control-sm rounded-5 ps-4" placeholder="Adresse mail">
                  <label for="id_email" class="form-label ms-3"> Adresse mail </label>
                </div>
                <div class="form-floating mt-1">
                  <textarea name="message" id="id_message" cols="30" rows="5" class="form-control rounded-5 ps-4" placeholder="Messages" style="height: auto;"></textarea>
                  <label for="id_message" class="form-label ms-3"> Messages </label>
                </div>
                <div class="row m-1">
                  <input type="submit" value="Nous contacter" class="btn btn-primary rounded-5">
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
</main>


{% endblock %}